version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/ag-grid-angular"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/ag-grid-community"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/ag-grid-enterprise"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/ag-grid-react"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/ag-grid-vue3"
    schedule:
      interval: "monthly"
