name: OSS Scorecard
on:
  workflow_dispatch:
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
  branch_protection_rule:
  push:
    branches: [ "latest" ]

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    # `publish_results: true` only works when run from the default branch. conditional can be removed if disabled.
    if: github.event.repository.default_branch == github.ref_name || github.event_name == 'pull_request'
    permissions:
      security-events: write
      id-token: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: "Upload artifact"
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: "Check Results"
        id: check_results
        run: |
          node external/ag-shared/scripts/ossf-scorecard/getAndCheckResults.mjs grid 7.1

      - name: Get previous run commit SHA
        id: prev-commit-sha
        uses: actions/cache/restore@v4
        with:
          restore-keys: |
            scorecard-prev-commit-
            scorecard-prev-commit-${{ github.ref }}
          path: ./commit-sha.txt
          key: scorecard-prev-commit-${{ github.ref }}-${{ github.sha }}

      - name: Load files into environment
        continue-on-error: true
        run: |
          if [ -f ./commit-sha.txt ]; then
          {
             echo 'PREV_COMMIT_SHA<<EOF'
             cat ./commit-sha.txt
             echo 'EOF'
          } >> $GITHUB_ENV
          else
            echo 'PREV_COMMIT_SHA_FILE not found'
          fi

      - name: Slack Notification
        uses: ./external/ag-shared/github/actions/slack-integration
        with:
          AG_LIBRARY: grid
          CTRF_REPORT_FILE: ./ctrf-report.json
          SLACK_BOT_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}
          SLACK_CHANNEL: '#ci-grid-gate'
          PREV_COMMIT_SHA: ./commit-sha.txt
          CURRENT_COMMIT_SHA: ${{ github.sha }}
          IS_SUCCESS: ${{ needs.check_results.result != '0' }}
